# Generated by Django 5.0.3 on 2024-03-19 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_agency_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='author_usersame',
            new_name='author_username',
        ),
    ]
